### ISSUE TITLE
Details for CREDS.cfg (Obtaining an Access Token)

### ISSUE THREAD

**Issue by AloftLab** [darwinex/darwin-api-tutorials#1]
Hi!

Am following tutorial and currently am stuck with error bellow:

>  File "C:\xxxxlib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-39-f60c04be2501>", line 1, in <module>
> --+--+--
>     api = DWX_API()
>   File "dwx_api.py", line 39, in __init__
> [KERNEL] Access & Refresh Tokens Retrieved Successfully
>     self._auth_headers = {'Authorization': 'Bearer {}'.format(self._auth._data['access_token'])}
> --+--+--
> KeyError: 'access_token'

And to be honest there is some guessing from my side what goes to creds.cfg file: 
username=my email?
password=pass for darwinex?
client_id=Username from darwinex?
client_secret= Api key?

Any help would be appriciated!

tnx

**Comment by integracore2** [comment]
Hi @matjazzh ,

This is described in the corresponding tutorial video below:
https://www.youtube.com/watch?v=tJjT1MdxhyI&list=PLv-cA-4O3y96EwRy0T6Y6CY52_x9Zdec9&index=2

The credentials required are:

Username=<your darwinex username>
Password=<your darwinex password>
client_id=<CLIENT ID provided to you by Darwinex when you requested API access>
client_secret=<CLIENT SECRET provided to you by Darwinex when you requested API access>

To obtain the latter two, please visit:
https://www.darwinex.com/data/darwin-api

**Comment by bukosabino** [comment]
Hi @integracore2 ,

I have seen the video, but I am not sure what values should I use to fill the `creds.cfg` file.

username=darwinex username
password=darwinex password
client_id=consumer key from https://www.darwinex.com/data/darwin-api
client_secret=consumer secret from https://www.darwinex.com/data/darwin-api

this is my error from oauth2 request:

{"error_description":"The authenticated client is not authorized to use this authorization grant type","error":"unauthorized_client"}
