### ISSUE TITLE
Quote vs Underlying Strategy UNIX Timestamps

### ISSUE THREAD

**Issue by caglarcankaya** [darwinex/darwin-api-tutorials#6]
I couldn't find functions such as get_return, get_data when I checked those were introduced from 8th video in playlist https://www.youtube.com/playlist?list=PLv-cA-4O3y971GdF958WoidF3HISpAiTf. 
Also when I get score data from DWX_Info_API and d_average from ftp server I see different timestamps with difference of 1 day and length of returned array is different so how can I combine them and fill the missing data.

**Comment by integracore2** [comment]
Hi @caglarcankaya ,

Quotes, Scores and Underlying Strategy data all have varying times of calculation -> hence updated timestamps differ.

Indexing any data structures such as pandas DataFrames therefore requires the API user to clearly define the indexing rationale first.

We have released a dedicated Python package over the last few months that enables users to access the DARWIN API, Raw DARWIN Data via FTP and our FTP Market Tick Data repository all from within one package:
https://pypi.org/project/darwinexapis/

We encourage you to use the above package from here on, as the codebase in this repository is no longer being updated (it was meant to serve as a series of detailed examples, building up to the package that is now available above).

You won't need to change any existing code based on this repository's codebase, and will benefit from considerably more features and functionality in the new package.

All the best!
